**Tensores**: unidades matriciles multidimensionales, con las que vamos a estar representando los pesos de las personas. Representan los pesos o concexiones entre neuronas

¿ Qué es un grafo ?
==
> En matemáticas y ciencias de la computación, un grafo (del griego grafos: dibujo, imagen) es un conjunto de objetos llamados vértices o nodos unidos por enlaces llamados aristas o arcos, que permiten representar relaciones binarias entre elementos de un conjunto.  Son objeto de estudio de la teoría de grafos.



<center><img src="https://upload.wikimedia.org/wikipedia/commons/5/57/6n-graf.png" style="width:200px;"/></center>


<center><h6><b style="color:#000;">Grafo con 6 vertices</b></h6></center>


¿ Qué es TensorFlow ?
==

TensorFlow es una librería de código abierto para cálculo numérico, usando como forma de programación grafos de flujo de datos. 
<ul>
    <li><b>Los nodos</b> en el grafo representan operaciones matemáticas, mientras que </li>
    <li><b>Las conexiones o links del grafo</b> representan los conjuntos de datos multidimensionales (tensores)  o arrays multidimensionales.</li>
</ul>

> Con esta librería somos capaces, entre otras operaciones, de construir y entrenar redes neuronales para detectar correlaciones y descifrar patrones, análogos al aprendizaje y razonamiento usados por los humanos.


<h1>¿Qué es un Tensor?</h1>

> Los tensores son matrices multidimensionales con un tipo uniforme (llamado dtype ). Puede ver todos los dtypes admitidos en tf.dtypes.DType a continuación:

> Referencia: https://www.tensorflow.org/guide/tensor

Tipos de datos definidos:

> Referencia: https://www.tensorflow.org/api_docs/python/tf/dtypes/DType

<ul>import tensorflow as tf
import numpy as np 
    <li>tf.float16: 16-bit half-precision floating-point.</li>
    <li>USAMOS ESTE tf.float32: 32-bit single-precision floating-point.</li>
    <li>tf.float64: 64-bit double-precision floating-point.</li>
    <li>tf.bfloat16: 16-bit truncated floating-point.</li>
    <li>tf.complex64: 64-bit single-precision complex.</li>
    <li>tf.complex128: 128-bit double-precision complex.</li>
    <li>tf.int8: 8-bit signed integer.</li>
    <li>tf.uint8: 8-bit unsigned integer.</li>
    <li>tf.uint16: 16-bit unsigned integer.</li>
    <li>tf.uint32: 32-bit unsigned integer.</li>
    <li>tf.uint64: 64-bit unsigned integer.</li>
    <li>tf.int16: 16-bit signed integer.</li>
    <li>tf.int32: 32-bit signed integer.</li>
    <li>tf.int64: 64-bit signed integer.</li>
    <li>tf.bool: Boolean.</li>
    <li>tf.string: String.</li>
    <li>tf.qint8: Quantized 8-bit signed integer.</li>
    <li>tf.quint8: Quantized 8-bit unsigned integer.</li>
    <li>tf.qint16: Quantized 16-bit signed integer.</li>
    <li>tf.quint16: Quantized 16-bit unsigned integer.</li>
    <li>tf.qint32: Quantized 32-bit signed integer.</li>
    <li>tf.resource: Handle to a mutable resource.</li>
    <li>tf.variant: Values of arbitrary types.</li>
    <li>The tf.as_dtype() function converts numpy types and string type names to a DType object.</li>
</ul>

> Si está familiarizado con NumPy , los tensores son (algo así como) como <b>np.arrays</b> .

> Casi todos los tensores <b>son inmutables</b> como las tuplas de Python: no se puede actualizar el contenido de un tensor, solo crear uno nuevo.

In [1]:
import tensorflow as tf
import numpy as np

<h2>Tensor de rango cero</h2>

> Aquí hay un tensor "escalar" o "rango 0". Un escalar contiene un valor único y no "ejes".

Rango cero = tiene un solo elemento.

In [4]:
rank_0_tensor = tf.constant(4.4)
print(rank_0_tensor)

# Se instancia a la clase constante que corresponde al tf

tf.Tensor(4.4, shape=(), dtype=float32)


<h2>Tensor de rango uno</h2>

> Un tensor de "vector" o de "rango 1" es como una lista de valores. Un vector tiene 1 eje:

> <b style="color:#f00;">Notar que lo toma como un vector vertical</b>

In [5]:
# Le damos como atributo una lista de valores
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


<h2>Tensor de rango 2</h2>

> Un tensor de "matriz" o "rango 2" tiene 2 ejes:

In [6]:
# Le damos una lista de listas (como un array de Python)
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)


tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


<h2>Tensor de rango 3</h2>

In [7]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],[15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],[25, 26, 27, 28, 29]],
])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


<h1>De TensorFlow a numpy</h1>

> Puede convertir un tensor en una matriz NumPy usando <b>np.array</b> o el método <b>tensor.numpy</b>:

In [8]:
np.array(rank_2_tensor)
#type(np.array(rank_2_tensor))

# Tensorflow y numpy son compatibles!

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

<h1>Matemática con tensores</h1>

> Podemos hacer matemáticas básicas con tensores, incluida la suma, la multiplicación por elementos y la multiplicación de matrices.

In [11]:
# Definimos dos tensores constantes de rango 2
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

# Suma
print(tf.add(a, b), "\n")

# Multiplicación (elemento a elemento)
print(tf.multiply(a, b), "\n")

# Multiplicación matricial
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [10]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



<h1>Acerca de las formas</h1>

Los tensores tienen formas. Algo de vocabulario:
<ul>
    <li><b style="font-size:20px; color:red;">Forma (Shape) :</b> La longitud (número de elementos) de cada una de las dimensiones de un tensor.</li>
<li><b style="font-size:20px; color:red;">Rango (rank ó degree ó order ó ndims):</b> Número de dimensiones del tensor. Un escalar tiene rango 0, un vector tiene rango 1, una matriz tiene rango 2. El rango de un tensor no es el mismo que el de una matriz. El rango de un tensor es el número de índices necesarios para seleccionar de forma única cada elemento del tensor.</li>
<li><b style="font-size:20px; color:red;">Eje o dimensión :</b> dimensión particular de un tensor.</li>
<li><b style="font-size:20px; color:red;">Tamaño : </b>el número total de elementos en el tensor, el vector de forma del producto</li>
</ul>

<h2>Forma del tensor</h2>

In [13]:
# Le pasamos las dimensiones
rank_4_tensor = tf.zeros([3, 2, 4, 5])
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)


In [14]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())
print("Rank", tf.rank(rank_4_tensor))


Type of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120
Rank tf.Tensor(4, shape=(), dtype=int32)


<h1>Ejemplos de tensores</h1>


In [15]:
# EJEMPLO DE TENSORES VARIABLES - nosotros lo vamos a instanciar
# de manera automática usando keras
string = tf.Variable("Esto es un string", tf.string)
numero = tf.Variable(333, tf.int16) # uint unsigned
floating = tf.Variable(4.89, tf.float64)
tensorrango2 = tf.Variable([["pera", "Manzana", "Manzana"], ["true", "false", "Manzana"]], tf.string)

In [16]:
print(tf.rank(tensorrango2))

tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
print("Forma de la matriz", tensorrango2.shape)

<h1>Cambio de forma</h1>

> El número de elementos de un tensor es el producto del tamaño de todas sus formas
> En ocaciones hay formas (shapes) que tienen el mismo numero de elementos
> haciendo conveniente cambiar la forma (shape) de un tensor.

In [17]:
# CREAMOS UN TENSOR DE FORMA [1,2,3] LLENO DE UNOS 

# Esto me da una lista que dentro tiene 2 listas con tres componentes cada uno
tensor1 = tf.ones([1,2,3])

# Esto me da dos listas que dentro tienen tres listas con 1 componente cada uno
tensor2 = tf.reshape(tensor1, [2,3,1])

# -1 le dice al tensor que calcule el tamaño de la dimensión en 
# este lugar lo cual realiza un cambio a la forma [3,2]
tensor3 = tf.reshape(tensor2, [3, -1])

In [18]:
print(tensor1)
tf.rank(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [19]:
print(tensor2)
tf.rank(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [20]:
print(tensor3)
tf.rank(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(), dtype=int32, numpy=2>